sudo: required
services:
    - docker

    script:
    - docker build -t mannydesigns/node .
    - docker images mannydesigns/node

    before_deploy:
        - docker login -u <username> -p <password>
    deploy:
        provide: script
        script: docker push mannydesigns/node
        on: 
           branch: master
